from sepaxml import SepaDD
import datetime, uuid

config = {
    "name": "Stefan Walkner",
    "IBAN": "AT495800010338048012",
    "BIC": "HYPVAT2B",
    "batch": True,
    "creditor_id": "DE26ZZZ00000000000",  # supplied by your bank or financial authority
    "currency": "EUR",  # ISO 4217
    # "instrument": "B2B",  # - default is CORE (B2C)
    "address": {
        # The address and all of its fields are optional but in some countries they are required
        "address_type": "ADDR",  # valid: ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
        # "department": "Head Office",
        "subdepartment": None,
        "street_name": "Quellenstr.",
        "building_number": "6",
        "postcode": "6890",
        "town": "Lustenau",
        "country": "AT",
        # "country_subdivision": None,
        # "lines": ["Line 1", "Line 2"],
    },
}
sepa = SepaDD(config, schema="pain.008.001.02", clean=True)

payment = {
    "name": "Thomas Vogel",
    "IBAN": "AT393700000003833332",
    "BIC": "DOSPAT2B",
    "amount": 5000,  # in cents
    "type": "RCUR",  # FRST,RCUR,OOFF,FNAL
    "collection_date": datetime.date.today(),
    "mandate_id": "1234",
    "mandate_date": datetime.date.today(),
    "description": "Test transaction",
    # "endtoend_id": str(uuid.uuid1()).replace("-", ""),  # autogenerated if obmitted
    "address": {
        # The address and all of its fields are optional but in some countries they are required
        "address_type": "ADDR",  # valid: ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
        # "department": "Head Office",
        # "subdepartment": None,
        "street_name": "Jahnstr.",
        "building_number": "8",
        "postcode": "6890",
        "town": "Lustenau",
        "country": "AT",
        # "country_subdivision": None,
        # "lines": ["Line 1", "Line 2"],
    },
}
sepa.add_payment(payment)

print(sepa.export(validate=True))
